Add math logic to calculator
AmineHLub/math-magician pull request #3
Opened 2021-10-20 16:58 UTC by AmineHLub

<h1> Summary </h1>

- Add math logic using given files calculate.js & operate.js
- Add BIG dependency
- Remove manifest from html

2021-10-20 17:16 UTC, Georjane requested changes
### Hello, @AmineHLub, ✋🏽 

Good job so far! You have a very professional Readme file, your PR is professional and you have a good mastery of git-flow. Your linters are all passing, I applaud that too.
However, we have a few more changes to make in order to meet all requirements for this project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding! 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝 

_Code Reviewer
**[Jane](https://witahgeorjane.tech/)**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-10-20 17:16 UTC, Georjane commented on src/components/Calculator.js
>  export default class Calculator extends Component {
- [ ] Your calculator works perfectly well but can you please implement the use of life cycle methods as this was one of the learning objectives of this project

2021-10-21 13:25 UTC, AmineHLub commented on src/components/Calculator.js
>  export default class Calculator extends Component {
Hello, @Georjane I did read about implementing life cycle. And I believe there is no need for implementing it yet. My project is one component only and there is nothing much, no API call no async functions yet.. I tried and Implemented an update method to show the current operation (using previous state snapshot). I can use its return like this 
![image](https://user-images.githubusercontent.com/83329154/138287273-519007ac-3a9e-40d0-a461-2f5b85a1e1b1.png)

but that would not look like the given UI. Should I go ahead with it ?

2021-10-21 13:34 UTC, Georjane commented on src/components/Calculator.js
>  export default class Calculator extends Component {
Hi @AmineHLub, please which life cycle method did you use to implement this exactly?

2021-10-21 13:41 UTC, AmineHLub commented on src/components/Calculator.js
>  export default class Calculator extends Component {
Hey @Georjane . Thank you very much for responding quickly it's appreciated. I used `componentDidUpdate`. exactly as 

```
  componentDidUpdate(prevProps, prevState) {
    const fullOperation = () => {
      if (prevState.total && prevState.operation && prevState.next) {
        return (
          <p className="full-operation">
            {prevState.total}
            {' '}
            {prevState.operation}
            {' '}
            {prevState.next}
            {' '}
          </p>
        );
      }
      return null;
    };
    return (
      fullOperation()
    );
  }
```

2021-10-21 13:45 UTC, Georjane commented on src/components/Calculator.js
>  export default class Calculator extends Component {
Great! This is looks perfect! I think the learning objectives here have all been attained.👍💯

2021-10-21 13:50 UTC, AmineHLub commented on src/components/Calculator.js
>  export default class Calculator extends Component {
@Georjane I hope you can know how much your comment relieved me :relieved: . Thank you very much I will push the updates and ask for another code review

2021-10-21 14:02 UTC, Emmyn5600 approved these changes
Hi, @AmineHLub 

Good job so far! 👏🏼

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous reviewer.

 #### Optional suggestions
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-10-21 14:14 UTC, merged